---
title: "Causal Inference -- Network Tutorial"
author: "Tyler Maule"
date: "3/10/2021"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(igraph)
```


```{r}
load("ICPSR_37070_2/DS0001/df_37070_0001_Data.rda")
student_df <- da37070.0001
head(student_df,10)
```

```{r}
student_df %>% group_by(SCHTREAT) %>% count(SCHTREAT)
```

```{r}
student_df2 <- student_df %>% filter (SCHTREAT == "(1) Treatment school (Roots meetings 2012-2013)") %>% drop_na(TREAT) %>% drop_na(UID)

student_df2  %>% group_by(SCHID,TREAT) %>% count(TREAT)
```

```{r}
student_df2$SIMPLE_TRT <- ifelse(student_df2$TREAT == "(1) Treatment", "(1) Treatment", "(2) Control")

student_df2  %>% group_by(SCHID,SIMPLE_TRT) %>% count(SIMPLE_TRT)
```

```{r}
student_df2[,c("UID","SCHID","ID","SCHRB","ST1", "ST2","ST3","ST4","ST5","ST6","ST7","ST8","ST9","ST10","CN1","CN2","CN3","CN4","CN5","BF1","BF2")]
```

```{r}
student_edges.df <- student_df2[,c("SCHID","ID","ST1", "ST2","ST3","ST4","ST5","ST6","ST7","ST8","ST9","ST10","CN1","CN2","CN3","CN4","CN5","BF1","BF2")]
names(student_edges.df)<- c("SCHID","ID","RST1", "RST2","RST3","RST4","RST5","RST6","RST7","RST8","RST9","RST10","RCN1","RCN2","RCN3","RCN4","RCN5","RBF1","RBF2")
#student_edges.list <- split(student_edges.df, seq(nrow(student_edges.df)))
#student_edges.list

student_edges.df <- student_edges.df %>% tidyr::pivot_longer(
  cols = starts_with("R"),
  names_to = "STUDENT_REL",
  values_to = "STUDENT_REL_ID"
) %>% drop_na()

student_edges.df$STUDENT_REL_ID <- as.factor(student_edges.df$STUDENT_REL_ID)

student_edges.df
```

```{r}
student_edges_s1.df <- student_edges.df %>% filter(SCHID == 1)
student_edges_s1.df <- student_edges_s1.df[,c("ID","STUDENT_REL_ID")]

student_edges_s1.df
```

```{r}
school1.graph <- graph_from_edgelist(as.matrix(student_edges_s1.df), directed=FALSE)

summary(school1.graph)
```

```{r}
edge_density(school1.graph)
```

```{r}
igraph_options(vertex.size = 3, vertex.label = NA, edge.arrow.size = 0.5)
plot(school1.graph, layout = layout_in_circle)
```
```{r}
plot(school1.graph, layout = layout_with_fr)
```

```{r}
plot(school1.graph, layout = layout_with_kk)

```

